<a href="https://colab.research.google.com/github/hrcn81/commonplace/blob/main/Commong.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np
import seaborn as sns
import statistics as stat

In [ ]:
data =  [1, 2, 3, 4, 4, 4, 4, 5, 6, 7, 7, 7, 8]
sum(data)

62

In [ ]:
len(data)

13

In [ ]:
sum(data) / len(data)

4.769230769230769

In [ ]:
stat.mean(data)

4.769230769230769

In [ ]:
datan = np.array(data)
datap = pd.DataFrame({'Attribute': data})

In [ ]:
datan

array([1, 2, 3, 4, 4, 4, 4, 5, 6, 7, 7, 7, 8])

In [ ]:
datap

Attribute
0           1
1           2
2           3
3           4
4           4
5           4
6           4
7           5
8           6
9           7
10          7
11          7
12          8

In [ ]:
df = sns.load_dataset('mpg')

In [ ]:
df.head()

mpg  cylinders  displacement  horsepower  weight  acceleration  \
0  18.0          8         307.0       130.0    3504          12.0   
1  15.0          8         350.0       165.0    3693          11.5   
2  18.0          8         318.0       150.0    3436          11.0   
3  16.0          8         304.0       150.0    3433          12.0   
4  17.0          8         302.0       140.0    3449          10.5   

   model_year origin                       name  
0          70    usa  chevrolet chevelle malibu  
1          70    usa          buick skylark 320  
2          70    usa         plymouth satellite  
3          70    usa              amc rebel sst  
4          70    usa                ford torino

In [ ]:
df.columns

Index(['mpg', 'cylinders', 'displacement', 'horsepower', 'weight',
       'acceleration', 'model_year', 'origin', 'name'],
      dtype='object')

In [ ]:
stat.mean(df['mpg'])

23.514572864321607

In [ ]:
df[['mpg','weight']].mean()

mpg         23.514573
weight    2970.424623
dtype: float64

In [ ]:
!pip install scipy

In [ ]:
import numpy as np
from scipy.stats import mode

data = np.array([
    [1, 2, 3, 4, 5],
    [2, 3, 4, 5, 6],
    [3, 4, 5, 6, 7]
])

# Flatten the 2D array to 1D before using mode
flattened_data = data.flatten()

# Calculate mode using SciPy's mode function
mode_result = mode(flattened_data)
mode_value = mode_result.mode  # mode_result.mode is already an array

print("Mode of 2D array:", mode_value)

Mode of 2D array: 3


In [ ]:
import numpy as np
from scipy.stats import mode

data_3d = np.array([
    [[1, 2, 3], [4, 5, 6]],
    [[2, 3, 4], [5, 6, 7]],
    [[3, 4, 5], [6, 7, 8]]
])

# Flatten the 3D array to 1D before using mode
flattened_data_3d = data_3d.flatten()

# Calculate mode using SciPy's mode function
mode_result_3d = mode(flattened_data_3d)
mode_value_3d = mode_result_3d.mode  # mode_result_3d.mode is already an array

print("Mode of 3D array:", mode_value_3d)


Mode of 3D array: 3


# **NUMPY Practice**:

In [ ]:
# Python Program illustrating
# numpy.zeros method

import numpy as geek

b = geek.zeros(2, dtype = int)
print("Matrix b : \n", b)

a = geek.zeros([2, 2,3], dtype = int)
print("\nMatrix a : \n", a)

c = geek.zeros([3, 3])
print("\nMatrix c : \n", c)

Matrix b : 
 [0 0]

Matrix a : 
 [[[0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]]]

Matrix c : 
 [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [ ]:
# Python Program illustrating
# numpy.ones method

import numpy as geek

b = geek.ones(2, dtype = int)
print("Matrix b : \n", b)

a = geek.ones([2, 2], dtype = int)
print("\nMatrix a : \n", a)

c = geek.ones([3, 3])
print("\nMatrix c : \n", c)

Matrix b : 
 [1 1]

Matrix a : 
 [[1 1]
 [1 1]]

Matrix c : 
 [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [ ]:
print(type(c))
print(c.dtype)

<class 'numpy.ndarray'>
float64


In [ ]:
ar1 = geek.random.random((3,4))
ar1

array([[0.16391625, 0.99577297, 0.18180887, 0.77136587],
       [0.75362944, 0.30444265, 0.58579795, 0.29452263],
       [0.25406537, 0.63251549, 0.69335476, 0.46888371]])

In [ ]:
ar2 = geek.reshape(ar1,(3,2,2))
print(ar2)
print(ar2.ndim)
print(ar2.size)
print(ar2.shape)

[[[0.16391625 0.99577297]
  [0.18180887 0.77136587]]

 [[0.75362944 0.30444265]
  [0.58579795 0.29452263]]

 [[0.25406537 0.63251549]
  [0.69335476 0.46888371]]]
3
12
(3, 2, 2)


In [ ]:
ar2.flatten()

array([0.16391625, 0.99577297, 0.18180887, 0.77136587, 0.75362944,
       0.30444265, 0.58579795, 0.29452263, 0.25406537, 0.63251549,
       0.69335476, 0.46888371])

In [ ]:
are = geek.array([])
for i in ar2:
  for j in i:
      are = geek.append(are,j)
print(geek.array(are))
print(type(are))

[0.16391625 0.99577297 0.18180887 0.77136587 0.75362944 0.30444265
 0.58579795 0.29452263 0.25406537 0.63251549 0.69335476 0.46888371]
<class 'numpy.ndarray'>


In [ ]:
arrd = geek.random.randint((2,3))
arrd

array([0, 0])

In [ ]:
# arrd + 10             # array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])
# arrd * 10             # array([ 10,  20,  30,  40,  50,  60,  70,  80,  90, 100])
# arrd - 10             # array([-9, -8, -7, -6, -5, -4, -3, -2, -1,  0])
# arrd / 10             # array([0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. ])

In [ ]:
arra = geek.arange(1,10).reshape(3,3)
arra

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
armx1 = arra.max(axis = 1)
armx1

array([3, 6, 9])

In [ ]:
armx0 = arra.max(axis = 0)
armx0

array([7, 8, 9])

In [ ]:
armn1 = arra.min(axis = 1)
armn1

array([1, 4, 7])

In [ ]:
armn0 = arra.min(axis = 0)
armn0

array([1, 2, 3])

In [ ]:
arra.sum()

45

In [ ]:
arra

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
arrb = geek.arange(1001,1010).reshape(3,3)
arrb

array([[1001, 1002, 1003],
       [1004, 1005, 1006],
       [1007, 1008, 1009]])

In [ ]:
print(arra + arrb)

[[1002 1004 1006]
 [1008 1010 1012]
 [1014 1016 1018]]


In [ ]:
print(arra * arrb)        # Element wise operation

[[1001 2004 3009]
 [4016 5025 6036]
 [7049 8064 9081]]


In [ ]:
arra

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
arrb

array([[1001, 1002, 1003],
       [1004, 1005, 1006],
       [1007, 1008, 1009]])

In [ ]:
(1*1001) + (2*1004) + (3*1007)

6030

In [ ]:
arra.dot(arrb)

array([[ 6030,  6036,  6042],
       [15066, 15081, 15096],
       [24102, 24126, 24150]])

In [ ]:
arrb.dot(arra)

array([[12030, 15036, 18042],
       [12066, 15081, 18096],
       [12102, 15126, 18150]])